# RED NEURONAL CON TENSORFLOW
### Z = W*X + B

In [10]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

Iniciamos las variables random

In [11]:
random_a = np.random.uniform(0,50,(4,4))
random_b = np.random.uniform(0,50,(4,1))

Creamos placeholders

In [12]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [13]:
suma = a + b
mult = a * b

In [15]:
with tf.Session() as sesion:
    res_suma = sesion.run(suma,feed_dict={a:random_a, b:random_b})
    res_mult = sesion.run(mult,feed_dict={a:random_a, b:random_b})
    print(res_suma)
    print('\n')
    print(res_mult)

[[50.396385 81.62652  40.00475  70.46698 ]
 [68.62365  50.8552   50.822556 47.468285]
 [85.82045  66.85443  71.542786 75.49535 ]
 [90.41897  62.7514   54.53601  54.47734 ]]


[[ 535.434   1633.9199   169.91946 1241.3954 ]
 [1160.069    624.1613   623.1766   522.00964]
 [1807.6381  1103.8201  1277.802   1424.4797 ]
 [2033.2738   692.2578   294.06708  291.2233 ]]


## Red neuronal
Con 10 características y 4 neuronas.

In [27]:
caracteristicas = 10
neuronas = 4
x = tf.placeholder(tf.float32,(None, caracteristicas))
W = tf.Variable(tf.random.normal([caracteristicas, neuronas]))
b = tf.Variable(tf.ones([neuronas]))
initializer = tf.global_variables_initializer()

In [28]:
multip = tf.matmul(x,W)
z = tf.add(multip,b)
activation = tf.sigmoid(z)
x_values = np.random.random([1,caracteristicas])

In [29]:
with tf.Session() as sesion:
    sesion.run(initializer)
    final_result = sesion.run(activation, feed_dict={x:x_values})

In [30]:
print(final_result)

[[0.8431963  0.16289714 0.99621624 0.64031935]]
