In [25]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [26]:
mensaje1= tf.constant('Hola ')
mensaje2= tf.constant('Mundo')

In [27]:
with tf.Session() as sesion:
    resultado = sesion.run(mensaje1 + mensaje2)

In [28]:
resultado

b'Hola Mundo'

In [29]:
a = tf.constant(10)
b = tf.constant(5)

In [30]:
with tf.Session() as sesion:
    resultado = sesion.run(a+b)

In [31]:
resultado

15

In [32]:
constante = tf.constant(15)
matrix1 = tf.fill((6,6),10)
matrix2 = tf.random_normal((5,5))
matrix3 = tf.random_uniform((4,4), minval=0, maxval=5)
matrix_cero = tf.zeros((2,2))
matrix_ones = tf.ones((3,3))

In [33]:
operaciones = [constante, matrix1, matrix2, matrix3, matrix_cero, matrix_ones]

In [36]:
with tf.Session() as sesion:
    for op in operaciones:
        print(sesion.run(op))
        print('\n')

15


[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


[[ 1.3525643  -0.75924814 -1.0169756  -0.36312884 -1.4651896 ]
 [ 0.17353289 -1.0775832  -0.5495703   0.0522418  -0.18653244]
 [ 0.27036947 -1.6401066  -0.2598544  -0.17467844 -0.92619866]
 [-0.41615707 -0.44647217 -0.71559197  0.17150886 -0.09672331]
 [-0.2665622  -0.6050785  -0.1279329   1.013347   -0.13937205]]


[[0.6277275  3.053711   3.0178313  1.8723798 ]
 [4.0647607  4.2765355  4.8167515  4.4455333 ]
 [3.860044   4.16291    0.6355983  1.0568303 ]
 [1.0756427  1.0737628  1.0277891  0.81300795]]


[[0. 0.]
 [0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


